# golangci-lint configuration
run:
  go: '1.21.0'
  timeout: 5m
  tests: true
  build-tags: []
  skip-dirs:
    - vendor
    - .git
  skip-files: []

linters:
  enable:
    - gofmt      # Format check
    - goimports  # Import organization
    - govet      # Go vet
    - errcheck   # Check error handling
    - staticcheck # Static analysis
    - gosimple   # Simplifications
    - ineffassign # Ineffective assignments
    - unused     # Unused code
    - misspell   # Spelling mistakes
    - godoc      # Documentation check
  disable:
    - gosec      # Will enable later
    - dupl       # Code duplication (will enable later)

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/dylan-gluck/spcstr
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - errcheck
        - godoc